name = "hnumerics"
description = "Operations for dual numbers"
version = "1.0.0"

authors = ["Rene Hartmann"]
maintainers = ["Rene Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "BSD-3-Clause"
website = "https://github.com/rehartmann/hnumerics"
tags = ["dual-numbers", "numerics"]
